#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config click_to_focus 	  true
bspc config focus_follows_pointer true
#bspc config normal_border_color   "#253047"
bspc config normal_border_color   "#2E3440"
#bspc config focused_border_color  "#4287f5"
bspc config focused_border_color  "#2E3440"
bspc config presel_feedback_color "#ffffff"
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Mouse Pointer
xsetroot -cursor_name left_ptr

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a zoom desktop='^6' follow=on
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Lutris desktop='^4' follow=on
bspc rule -a code-oss desktop='^2' follow=on
bspc rule -a Thunar desktop='^10' follow=on
bspc rule -a Zathura desktop='^8' follow=on 
bspc rule -a st-256color state=floating
bspc rule -a mplayer2 state=floating

# Autostart
sxhkd &
lxsession &
picom -b &
~/.config/polybar/launch.sh
nitrogen --restore &
dunst &
flameshot

# Clipboard
killall xfce4-clipman
xfce4-clipman &
