#! /bin/sh

# Autostart
sxhkd &
lxsession &
picom --experimental-backends &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh

# Clipboard
killall xfce4-clipman
xfce4-clipman &

bspc monitor HDMI-A-1 -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config click_to_focus 	  true
bspc config focus_follows_pointer true
bspc config focused_border_color "#3DE1CC"
bspc config presel_feedback_color "#ffffff"
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Mouse Pointer
xsetroot -cursor_name left_ptr

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a discord desktop='^6' follow=on
bspc rule -a zoom desktop='^6' follow=on
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
